### ISSUE TITLE
是不是少了一个函数

### ISSUE THREAD

**Issue by tangtang666** [MUZLATAN/ffmpeg_rtsp_mpp#1]
error: ‘MppDecode’ has not been declared
void MppDecode::conv_yuv420_to_mat()

**Comment by MUZLATAN** [comment]
修改了一些东西，加了一个yuv 转mat的函数， 测试过能用，但是需要自己在rk的板子上安装opencv 才能使用， 故注释掉了，这个版本的是可以直接编译运行

**Comment by MUZLATAN** [comment]
重新添加了一个整的YUV420SP2Mat()函数

**Comment by tangtang666** [comment]
> 重新添加了一个整的YUV420SP2Mat()函数

谢谢，我拉了再试试，我上次是用你的历史提交的版本跑通了的

**Comment by tangtang666** [comment]
我把你注释的那行保存的代码开着了 保存下来的图片全部都是空的 我转成bgr显示size也是0
//                        cv::imwrite("./"+std::to_string(count++)+".jpg", rgbImg);

**Comment by MUZLATAN** [comment]
你似乎没有转码成功吧，opencv的库链接正确了吗

**Comment by tangtang666** [comment]
改了代码已经解决来

**Comment by testwen00** [comment]
@tangtang666 请问你怎么解决的？
