### ISSUE TITLE
输出的YUV文件size为0？

### ISSUE THREAD

**Issue by siyl** [MUZLATAN/ffmpeg_rtsp_mpp#4]
修改main.cpp如下：
char filepath[] = "rtsp://admin:23@xxx.xxx.xxx.xxx:554/h264/ch39/sub/av_stream";// 自己的rtsp 地址
...
   // paramter for resource malloc
    RK_U32 width        = 1280;
    RK_U32 height       = 720;
    MppCodingType type  = MPP_VIDEO_CodingAVC;
...

//// 初始化
    MPP_RET ret         = MPP_OK;
    size_t file_size    = 8*1024;

**Comment by siyl** [comment]
已解决

**Comment by gitccl** [comment]
请问你是怎么解决的呀
