### ISSUE TITLE
h265多路rtsp解码报错，导致程序异常退出

### ISSUE THREAD

**Issue by SpiceGL** [MUZLATAN/ffmpeg_rtsp_mpp#9]
你好，我参考你的例子，自己改成了4路拉流解码，在拉取h264时没有问题。但是在拉取h265时（已修改解码类型：MppCodingType type  = MPP_VIDEO_CodingHEVC;），发现有两种报错退出方式：free() invalid pointer、corrupted size vs. prev size。
我开始以为是我自己的改写有问题，于是使用本项目的原版例子，将main函数改名为thread0，然后在新的main函数中以4个线程分别调用，结果还是触发了上述报错。而在h264的解码时并没有遇到这个问题。
我的测试设备是rv1109和rv1126，mpp版本是最新1.0.4，均存在上述问题。请问这个是什么原因导致的呢？

新的main函数：
```
int main(int argc, char* argv[])
{
    std::string mode = "0";
    if (argc >= 2)
        mode = argv[1];

    if (mode == "0")
    {
        std::thread td0(thread0);
        td0.detach();

        std::thread td1(thread0);
        td1.detach();

        std::thread td2(thread0);
        td2.detach();

        std::thread td3(thread0);
        td3.detach();
    }

    while (1)
    {
        printf("send buffer\n");
        msleep(36);
    }
}
```

**Comment by stz-source** [comment]
您好，请问您解决了吗？如何把H265拉过来，我修改了MPP_VIDEO_CodingHEVC，能检测到有流过来，但是解码出来的frame都是NULL

**Comment by stz-source** [comment]
> 你好，我参考你的例子，自己改成了4路拉流解码，在拉取h264时没有问题。但是在拉取h265时（已修改解码类型：MppCodingType type = MPP_VIDEO_CodingHEVC;），发现有两种报错退出方式：free() invalid pointer、corrupted size vs. prev size。 我开始以为是我自己的改写有问题，于是使用本项目的原版例子，将main函数改名为thread0，然后在新的main函数中以4个线程分别调用，结果还是触发了上述报错。而在h264的解码时并没有遇到这个问题。 我的测试设备是rv1109和rv1126，mpp版本是最新1.0.4，均存在上述问题。请问这个是什么原因导致的呢？
> 
> 新的main函数：
> 
> ```
> int main(int argc, char* argv[])
> {
>     std::string mode = "0";
>     if (argc >= 2)
>         mode = argv[1];
> 
>     if (mode == "0")
>     {
>         std::thread td0(thread0);
>         td0.detach();
> 
>         std::thread td1(thread0);
>         td1.detach();
> 
>         std::thread td2(thread0);
>         td2.detach();
> 
>         std::thread td3(thread0);
>         td3.detach();
>     }
> 
>     while (1)
>     {
>         printf("send buffer\n");
>         msleep(36);
>     }
> }
> ```您好，请问您解决了吗？如何把H265拉过来，我修改了MPP_VIDEO_CodingHEVC，然后ffmpeg拉流能拉h265过来，packet的size都大于0，能检测到有流过来，但是在decode_simple里面解码出来的frame都是NULL，然后一直不会进去那个if(frame)的判断语句。

**Comment by SpiceGL** [comment]
> > 你好，我参考你的例子，自己改成了4路拉流解码，在拉取h264时没有问题。但是在拉取h265时（已修改解码类型：MppCodingType type = MPP_VIDEO_CodingHEVC;），发现有两种报错退出方式：free() invalid pointer、corrupted size vs. prev size。 我开始以为是我自己的改写有问题，于是使用本项目的原版例子，将main函数改名为thread0，然后在新的main函数中以4个线程分别调用，结果还是触发了上述报错。而在h264的解码时并没有遇到这个问题。 我的测试设备是rv1109和rv1126，mpp版本是最新1.0.4，均存在上述问题。请问这个是什么原因导致的呢？
> > 新的main函数：
> > ```
> > int main(int argc, char* argv[])
> > {
> >     std::string mode = "0";
> >     if (argc >= 2)
> >         mode = argv[1];
> > 
> >     if (mode == "0")
> >     {
> >         std::thread td0(thread0);
> >         td0.detach();
> > 
> >         std::thread td1(thread0);
> >         td1.detach();
> > 
> >         std::thread td2(thread0);
> >         td2.detach();
> > 
> >         std::thread td3(thread0);
> >         td3.detach();
> >     }
> > 
> >     while (1)
> >     {
> >         printf("send buffer\n");
> >         msleep(36);
> >     }
> > }
> > ```您好，请问您解决了吗？如何把H265拉过来，我修改了MPP_VIDEO_CodingHEVC，然后ffmpeg拉流能拉h265过来，packet的size都大于0，能检测到有流过来，但是在decode_simple里面解码出来的frame都是NULL，然后一直不会进去那个if(frame)的判断语句。
> > ```

我的问题在这边解决了 https://github.com/rockchip-linux/mpp/issues/529
你的问题和我不一样，我只能猜测你这个现象像是解码类型和码流类型不一致，哪个环节出了问题。
